version: '2.0'
services:
  postgres:
    container_name: postgres
    environment:
    - DEBUG=false
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=masterkey
    image: postgres:10-alpine
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - /desenv/volumes/postgres/bkp:/opt/bkp
    - /desenv/volumes/data:/var/lib/postgresql/data
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
    - "9001:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /desenv/volumes/portainer/data:/data portainer/portainer
  pgAdmin4:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=postgres
    - PGADMIN_DEFAULT_PASSWORD=masterkey
    ports:
      - "15432:80"
  sonarQube:
    container_name: sonar_qube
    image: sonarqube:lts
    restart: always
    volumes:
    - /desenv/volumes/sonar/conf:/opt/sonarqube/conf
    - /desenv/volumes/sonar/data:/opt/sonarqube/data
    - /desenv/volumes/sonar/logs:/opt/sonarqube/logs
    - /desenv/volumes/sonar/extensions:/opt/sonarqube/extensions
    - /desenv/volumes/sonar/plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
    - "9000:9000"
